codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 2%
    patch:
      default:
        target: 90%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "**/*.config.*"
  - "**/*.d.ts"
  - "tests/**"
  - "src/pages/**"
  - "src/components/**/*.astro"
